INSERT INTO MARCAS VALUES
	(1,'SEAT','MADRID');
INSERT INTO MARCAS VALUES
	(2,'RENAULT','BARCELONA');
INSERT INTO MARCAS VALUES
	(3,'CITROEN','VALENCIA');
INSERT INTO MARCAS VALUES
	(4,'AUDI','MADRID');
INSERT INTO MARCAS VALUES
	(5,'OPEL','BILBAO');
INSERT INTO MARCAS VALUES
	(6,'BMW','BARCELONA');

INSERT INTO CLIENTES VALUES
	(1,'LUIS','GARCIA', 'MADRID');
INSERT INTO CLIENTES VALUES
	(2,'ANTONIO', 'LOPEZ', 'VALENCIA');
INSERT INTO CLIENTES VALUES
	(3,'JUAN','MARTIN', 'MADRID');
INSERT INTO CLIENTES VALUES
	(4,'MARIA', 'GARCIA', 'MADRID');
INSERT INTO CLIENTES VALUES
	(5, 'JAVIER', 'GONZALEZ', 'BARCELONA');
INSERT INTO CLIENTES VALUES
	(6, 'ANA', 'LOPEZ', 'BARCELONA');



INSERT INTO COCHES VALUES
	(1,'IBIZA','GLX');
INSERT INTO COCHES VALUES
	(2, 'IBIZA', 'GTI');
INSERT INTO COCHES VALUES
	(3,'IBIZA','GTD');
INSERT INTO COCHES VALUES
	(4, 'TOLEDO','GTD');
INSERT INTO COCHES VALUES
	(5,'CORDOBA','GTI');
INSERT INTO COCHES VALUES
	(6, 'MEGANE','1.6');
INSERT INTO COCHES VALUES
	(7, 'MEGANE','GTI');
INSERT INTO COCHES VALUES
	(8, 'LAGUNA','GTD');
INSERT INTO COCHES VALUES
	(9, 'LAGUNA','TD');
INSERT INTO COCHES VALUES
	(10, 'ZX','16V');
INSERT INTO COCHES VALUES
	(11, 'ZX','TD');
INSERT INTO COCHES VALUES
	(12, 'XANTIA','GTD');
INSERT INTO COCHES VALUES
	(13, 'A4','1.8');
INSERT INTO COCHES VALUES
	(14, 'MEGANE','1.6');
INSERT INTO COCHES VALUES
	(15, 'ASTRA','CARAVAN');
INSERT INTO COCHES VALUES
	(16, 'ASTRA','GTI');
INSERT INTO COCHES VALUES
	(17, 'CORSA','1.4');
INSERT INTO COCHES VALUES
	(18, '300','316I');
INSERT INTO COCHES VALUES
	(19, '500','525I');
INSERT INTO COCHES VALUES
	(20, '700','750I');

INSERT INTO CONCESIONARIO VALUES
	(1,'ACAR', 'MADRID');
INSERT INTO CONCESIONARIO VALUES
	(2,'BCAR', 'MADRID');
INSERT INTO CONCESIONARIO VALUES
	(3,'CCAR', 'BARCELONA');
INSERT INTO CONCESIONARIO VALUES
	(4,'DCAR', 'VALENCIA');
INSERT INTO CONCESIONARIO VALUES
	(5,'ECAR', 'BILBAO');


INSERT INTO DISTRIBUCION VALUES
	(1,1,3);
INSERT INTO DISTRIBUCION VALUES
	(1,5,7);
INSERT INTO DISTRIBUCION VALUES
	(1,6,7);
INSERT INTO DISTRIBUCION VALUES
	(2,6,5);
INSERT INTO DISTRIBUCION VALUES
	(2,8,10);
INSERT INTO DISTRIBUCION VALUES
	(2,9,10);
INSERT INTO DISTRIBUCION VALUES
	(3,10,5);
INSERT INTO DISTRIBUCION VALUES
	(3,11,3);
INSERT INTO DISTRIBUCION VALUES
	(3,12,5);
INSERT INTO DISTRIBUCION VALUES
	(4,13,10);
INSERT INTO DISTRIBUCION VALUES
	(4,14,5);
INSERT INTO DISTRIBUCION VALUES
	(5,15,10);
INSERT INTO DISTRIBUCION VALUES
	(5,16,20);
INSERT INTO DISTRIBUCION VALUES
	(5,17,8);
INSERT INTO DISTRIBUCION VALUES
	(6,19,3);


INSERT INTO MARCO VALUES
	(1,1);
INSERT INTO MARCO VALUES
	(1,2);
INSERT INTO MARCO VALUES
	(1,3);
INSERT INTO MARCO VALUES
	(1,4);
INSERT INTO MARCO VALUES
	(1,5);
INSERT INTO MARCO VALUES
	(2,6);
INSERT INTO MARCO VALUES
	(2,7);
INSERT INTO MARCO VALUES
	(2,8);
INSERT INTO MARCO VALUES
	(2,9);
INSERT INTO MARCO VALUES
	(3,10);
INSERT INTO MARCO VALUES
	(3,11);
INSERT INTO MARCO VALUES
	(3,12);
INSERT INTO MARCO VALUES
	(4,13);
INSERT INTO MARCO VALUES
	(4,14);
INSERT INTO MARCO VALUES
	(5,15);
INSERT INTO MARCO VALUES
	(5,16);
INSERT INTO MARCO VALUES
	(5,17);
INSERT INTO MARCO VALUES
	(6,18);
INSERT INTO MARCO VALUES
	(6,19);
INSERT INTO MARCO VALUES
	(6,20);

INSERT INTO VENTAS VALUES
	(1,1,1,'BLANCO');
INSERT INTO VENTAS VALUES
	(1,2,5,'ROJO');
INSERT INTO VENTAS VALUES
	(2,3,8,'BLANCO');
INSERT INTO VENTAS VALUES
	(2,1,6,'ROJO');
INSERT INTO VENTAS VALUES
	(3,4,11,'ROJO');
INSERT INTO VENTAS VALUES
	(4,5,14,'VERDE');

ALTER TABLE COCHES ADD COLUMN PRECIO INT(5) DEFAULT 15000;
ALTER TABLE VENTAS ADD COLUMN PRECIOFINAL INT(5) DEFAULT 14000;









