drop database if exists autos;
create database autos;
use autos;

CREATE TABLE MARCAS(
	CIFM INT(4),
	NOMBRE VARCHAR (15)  NOT NULL,
	CIUDAD VARCHAR (20)  NOT NULL,
	CONSTRAINT CP_CIFM PRIMARY KEY (CIFM)
);


CREATE TABLE CLIENTES(
	DNI INT(4)  PRIMARY KEY,
	NOMBRE VARCHAR (15) NOT NULL,
	APELLIDO VARCHAR (15)  NOT NULL,
	CIUDAD VARCHAR (15)  NOT NULL
);


CREATE TABLE COCHES(
	CODCOCHE INT(4)  PRIMARY KEY,
	NOMBRE VARCHAR (15) NOT NULL,
	MODELO VARCHAR (10)  NOT NULL
);


CREATE TABLE CONCESIONARIO (
	CIFC INT(4)  PRIMARY KEY,
	NOMBRE VARCHAR (10) NOT NULL,
	CIUDAD VARCHAR (10)
);


CREATE TABLE MARCO(
	CIFM INT(4),
	CODCOCHE INT(4),	
	CONSTRAINT  pk1 PRIMARY KEY (CIFM, CODCOCHE),
	CONSTRAINT  fk1 FOREIGN KEY(CIFM) REFERENCES MARCAS(CIFM) ON DELETE CASCADE,
	CONSTRAINT  fk2 foreign key (CODCOCHE) REFERENCES COCHES(CODCOCHE) ON DELETE CASCADE
);


CREATE TABLE VENTAS (
	CIFC INT(4),
	DNI INT(4),
	CODCOCHE INT(4),
	COLOR VARCHAR (10)  NOT NULL,
	CONSTRAINT pk2 PRIMARY KEY (CIFC, DNI, CODCOCHE),
	CONSTRAINT fk3 FOREIGN KEY(DNI) REFERENCES CLIENTES(DNI) ON DELETE CASCADE,
	 CONSTRAINT CA_CODCOCHE_VENTAS FOREIGN KEY(CODCOCHE) REFERENCES COCHES(CODCOCHE) ON DELETE CASCADE
);


CREATE TABLE DISTRIBUCION(
	CIFC INT(4), 
	CODCOCHE INT(4), 
	CANTIDAD INT(4) NOT NULL,
	CONSTRAINT CP_CIFC_CODCOCHE PRIMARY KEY (CIFC, CODCOCHE),
CONSTRAINT CA_CIFC FOREIGN KEY(CIFC) REFERENCES CONCESIONARIO(CIFC) ON DELETE CASCADE,
CONSTRAINT CA_CODCOCHE_DISTRIBUCION FOREIGN KEY(CODCOCHE) REFERENCES COCHES(CODCOCHE) ON DELETE CASCADE
);
