create or replace FUNCTION DISTANCIA 
(
  COORDX1 IN NUMBER 
, COORDY1 IN NUMBER 
, COORDX2 IN NUMBER 
, COORDY2 IN NUMBER 
) RETURN VARCHAR2 AS 
BEGIN
  RETURN sqrt(power(COORDX2-COORDX1,2)+power(COORDY2-COORDY1,2));
END DISTANCIA;